[build-system]
build-backend = "hatchling.build"
requires = ["hatch-vcs", "hatchling"]

[project]
authors = [
  { email = "305301+whardier@users.noreply.github.com", name = "Shane Spencer" },
]
dependencies = []
description = "Recian JSON (orjson) Manifest"
dynamic = ["version"]
name = "recian-manifest-json-orjson"
readme = "README.md"
requires-python = ">=3.10"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
search_parent_directories = true
version_scheme = "python-simplified-semver"
