[build-system]
build-backend = "hatchling.build"
requires = ["hatch-vcs", "hatchling"]

[project]
authors = [
  { email = "305301+whardier@users.noreply.github.com", name = "Shane Spencer" },
]
dependencies = [
  "recian-auth-http-aws-sigv4>=0.0.1",
  "recian-transport-http>=0.0.1",
]
description = "Recian HTTP AWS S3 Lock"
dynamic = ["version"]
name = "recian-lock-http-aws-s3"
readme = "README.md"
requires-python = ">=3.10"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
search_parent_directories = true
version_scheme = "python-simplified-semver"
