[project]
name = "recian-client-http"
description = "Recian HTTP Client"
readme = "README.md"
authors = [
    { name = "Shane Spencer", email = "305301+whardier@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
recian-sdk = "recian_sdk:main"

[build-system]
build-backend = "hatchling.build"
requires = ["hatch-vcs", "hatchling"]

[tool.hatch.version]
source = "vcs"
