[build-system]
build-backend = "hatchling.build"
requires = ["hatch-vcs", "hatchling"]

[project]
authors = [
  { email = "305301+whardier@users.noreply.github.com", name = "Shane Spencer" },
]
dependencies = []
description = "Recian CLI"
dynamic = ["version"]
name = "recian-cli"
readme = "README.md"
requires-python = ">=3.10"

[project.scripts]
recian = "recian_cli.entrypoint:main"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
search_parent_directories = true
version_scheme = "python-simplified-semver"
