[dependency-groups]
dev = [
  "bandit[toml,yaml]>=1.8",
  "black[colorama]>=25.9",
  "commitizen>=4.9",
  "coverage[toml]>=7.10",
  "flake8-absolute-import>=1.0",
  "flake8-bandit>=4.1",
  "flake8-bugbear>=24.12",
  "flake8-builtins>=3.0",
  "flake8-comprehensions>=3.17",
  "flake8-isort>=6.1",
  "flake8-print>=5.0",
  "flake8-pyproject>=1.2",
  "flake8-return>=1.2",
  "flake8-use-pathlib>=0.3",
  "flake8>=7.3",
  "hypothesis[cli,pytest,zoneinfo]>=6.140",
  "isort[colors,plugins]>=6.1",
  "mypy[install-types]>=1.18",
  "pep8-naming>=0.15",
  "pre-commit>=4.3",
  "pycln>=2.5",
  "pytest-cov>=7.0",
  "pytest-env>=1.2",
  "pytest-mock>=3.15",
  "pytest-xdist[psutil]>=3.8",
  "pytest>=8.4",
  "sphinx>=8.1",
  "taplo>=0.9",
  "toml-sort>=0.24",
  "tox>=4.31",
]

[tool.uv.sources]
recian-api = { workspace = true }
recian-auth-http-aws-sigv4 = { workspace = true }
recian-cli = { workspace = true }
recian-lock-http-aws-dynamodb = { workspace = true }
recian-lock-http-aws-s3 = { workspace = true }
recian-manifest-json = { workspace = true }
recian-manifest-json-orjson = { workspace = true }
recian-sdk = { workspace = true }
recian-transport-http = { workspace = true }
recian-transport-http-aws-s3 = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]
