[project]
name = "recian-s3-client"
description = "Recian S3 Client"
readme = "README.md"
authors = [
    { name = "Shane Spencer", email = "305301+whardier@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
recian-s3-client = "recian_s3_client:main"

[build-system]
build-backend = "hatchling.build"
requires = ["hatch-vcs", "hatchling"]

[tool.hatch.version]
source = "vcs"
